# Generated by Django 6.1.1 on 2026-09-25 17:00

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HotelGuest',
            fields=[
                ('guest_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('id_passport', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=100)),
                ('post_code', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?\\d{7,15}$')])),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='HotelRoom',
            fields=[
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('building', models.CharField(choices=[('A', 'Building A'), ('B', 'Building B')], max_length=1)),
                ('room_number', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=8)),
                ('max_guests', models.PositiveSmallIntegerField(choices=[(2, 'Up to 2 guests'), (4, 'Up to 4 guests')])),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('building', 'room_number'), name='unique_room_per_building')],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number_of_guests', models.PositiveSmallIntegerField()),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='rooms.hotelguest')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='rooms.hotelroom')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('check_out__gt', models.F('check_in'))), name='check_out_after_check_in')],
            },
        ),
    ]
